name: AutoMerge!!

on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'Java CI with Gradle'

jobs:
  merge-me:
    name: Merge me!

    runs-on: ubuntu-latest

    steps:
      - name: Merge me!
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.KEY_TOKEN}}
          PRESET: DEPENDABOT_MINOR
