# This workflow will build a Docker container

name: DockerImage

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Login to GitHub Container Registry
       uses: docker/login-action@v1
       with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.KEY_TOKEN }}
   
    
     - uses: actions/checkout@v2
     - name: Set up JDK 11
       uses: actions/setup-java@v2
       with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
     - name: Build with Gradle Jib
       run: gradle jib
